### ISSUE TITLE
blocktimer on individual keys

### ISSUE THREAD

**Issue by 7efneBepMM2uGhfzmGpK** [256shadesofgrey/eso-light-attack-weave#10]
I got a skill that has a cast time of 0.8s so I need to increase my time until block to 800ms. 
Obviously it effects all keys. Can you help making the blocktimer individual per key?

**Comment by 256shadesofgrey** [comment]
I never use that feature myself, hence why it's turned off by default. So no, I do not have any intention to work on improving it.
