### ISSUE TITLE
Support for additional mouse buttons?

### ISSUE THREAD

**Issue by yukitteru** [256shadesofgrey/eso-light-attack-weave#11]
My weapon bar change is set to km5, but when I specify the parameter in the script: global barSwap: = "XButton2", then panel change does not work.

**Comment by Jivonchi** [comment]
How did you manage to solve this issue? Im facing the same problem here :/

**Comment by 256shadesofgrey** [comment]
@Jivonchi Check out #9 .

**Comment by Jivonchi** [comment]
Thank you very much for the super quick reply! Fixed it for me. Have a great day :)
