### ISSUE TITLE
Script isnt running

### ISSUE THREAD

**Issue by blotterdotter** [256shadesofgrey/eso-light-attack-weave#12]
Every time I try to run the script I got the same error message:

Error: The script contains syntax errors.

Here a screenshot:

![image](https://user-images.githubusercontent.com/83516275/116794083-cc249f80-aaca-11eb-9cb3-fa254cc601bc.png)

 Any ideas how to get the script running?

Regards

Mark

**Comment by 256shadesofgrey** [comment]
I'm pretty sure you have the same problem as the person had here:
https://github.com/256shadesofgrey/eso-light-attack-weave/issues/4

**Comment by blotterdotter** [comment]
Tried it the way you told the other guy and the script is running. Thank you!

**Comment by iSpotless** [comment]
So I am trying to get this macro to work and for some reason I am having the hardest time. Downloaded the file, made sure it had .ahk and had AutoHotKey running but it still wont run for me, maybe I am missing something. I use my 1 button to cast a spell and no attack comes out

**Comment by iSpotless** [comment]
Never mind, forgot to hit tab.... my bad. Great job on the script though.
