### ISSUE TITLE
using buttons for weapon set 1 and weaon set 2

### ISSUE THREAD

**Issue by ilreberli** [256shadesofgrey/eso-light-attack-weave#20]
I use the function keys to switch directly to weapon set 1 / weapon set 2 instead of swap weapon set.
As far I have found only change weapon set is considered in the configuration. Can you enhance this ?

![image](https://github.com/256shadesofgrey/eso-light-attack-weave/assets/37041620/4571f4b4-3960-41a0-abee-82b5b478d767)

**Comment by 256shadesofgrey** [comment]
Yes, I can do this. I would add 2 more keybinds that call the same bar swap function in the script.

Which keys specifically do you use to switch to the corresponding weapon sets?

**Comment by 256shadesofgrey** [comment]
I implemented it. You can find the corresponding settings [here](https://github.com/256shadesofgrey/eso-light-attack-weave/blob/e028bb4987227d0ef3715f31ecc953f1ec70a56a/eso-light-attack-weave.ahk#L35C1-L37C27). Make sure to set `swapToSpecificWeaponSet` to `true` and adjust your keybinds accordingly.

Please let me know if there are issues.

**Comment by ilreberli** [comment]
Helllo Dmitri

Thank you very much for help, but I got a runtime error. I am not a ahk-specialist and not able to fix this.
It looks strange for me, because the beginning looks the same as before.

regards
Albert


[cid:37df474b-989e-44cf-829b-3c139b878559]


________________________________
Von: Dmitri Ranfft ***@***.***>
Gesendet: Samstag, 26. August 2023 19:58
An: 256shadesofgrey/eso-light-attack-weave ***@***.***>
Cc: ilreberli ***@***.***>; Author ***@***.***>
Betreff: Re: [256shadesofgrey/eso-light-attack-weave] using buttons for weapon set 1 and weaon set 2 (Issue #20)


I implemented it. You can find the corresponding settings here<https://github.com/256shadesofgrey/eso-light-attack-weave/blob/e028bb4987227d0ef3715f31ecc953f1ec70a56a/eso-light-attack-weave.ahk#L35C1-L37C27>. Make sure to set swapToSpecificWeaponSet to true and adjust your keybinds accordingly.

Please let me know if there are issues.

**Comment by 256shadesofgrey** [comment]
What is the runtime error?

**Comment by ilreberli** [comment]
Wow - thats fast 🙂

Didnt you receive the screenshot ?

Error at line 1:

Line Text:  ;This script adds ...
Error:  This line does not contain a recognized action.


________________________________
Von: Dmitri Ranfft ***@***.***>
Gesendet: Sonntag, 27. August 2023 07:23
An: 256shadesofgrey/eso-light-attack-weave ***@***.***>
Cc: ilreberli ***@***.***>; Author ***@***.***>
Betreff: Re: [256shadesofgrey/eso-light-attack-weave] using buttons for weapon set 1 and weaon set 2 (Issue #20)


What is the runtime error?

**Comment by 256shadesofgrey** [comment]
No, there is no screenshot here, just some string of text. I guess github doesn't handle it very well when you reply via email directly.

This is weird. This line is just a comment. And the script did work for me before... Try removing line 6, the `#UseHook`. I added it along with the feature you requested because the script was suddenly behaving differently from how it did the last time I used it (the hotkeys were activating themselves repeatedly without this line), and that was a fix for it for me, but maybe it causes some unexpected behavior with your setup since that's not how it worked half a year ago either.

**Comment by ilreberli** [comment]
I tried to remove #UseHook with no success.
Then I reinstalled AHK  with both versions 1.1 and 2.0.
The old very simple ahk-1 script of my own still works, your script has still an error.
As far I know, ahk should detect itself the needed version.  Surprisingly it worked yesterday.


________________________________
Von: Dmitri Ranfft ***@***.***>
Gesendet: Sonntag, 27. August 2023 07:38
An: 256shadesofgrey/eso-light-attack-weave ***@***.***>
Cc: ilreberli ***@***.***>; Author ***@***.***>
Betreff: Re: [256shadesofgrey/eso-light-attack-weave] using buttons for weapon set 1 and weaon set 2 (Issue #20)


No, there is no screenshot here, just some string of text. I guess github doesn't handle it very well when you reply via email directly.

This is weird. This line is just a comment. And the script did work for me before... Try removing line 6, the #UseHook. I added it along with the feature you requested because the script was suddenly behaving differently from how it did the last time I used it (the hotkeys were activating themselves repeatedly without this line), and that was a fix for it for me, but maybe it causes some unexpected behavior with your setup since that's not how it worked half a year ago either.

**Comment by 256shadesofgrey** [comment]
This script was made for AHKv1, v2 has different syntax, so I don't think it will work without any adjustments. So definitely use 1.1, not 2.

Does the old version of my script that you used yesterday still work for you?

**Comment by ilreberli** [comment]
yes, except the swap weapon set

**Comment by ilreberli** [comment]
sorry - wrong answer !  

I do not have the old version from yesterday

**Comment by 256shadesofgrey** [comment]
That should be the version from [this commit](https://github.com/256shadesofgrey/eso-light-attack-weave/tree/611cb04de6b4186d23f00dad6243778cc1119b08).

I will also try updating autohotkey now to see if it may be an issue with a newer version. I'm currently running v1.1.31.01, and the latest is v1.1.37.01.

**Comment by ilreberli** [comment]
I used the old version (4 years ago) from your code and it doesnt work anymore !?
I also restarted the pc, but doesn't help. I am not sure, but I had some Microsoft updates last night (they do not ask).

**Comment by 256shadesofgrey** [comment]
I just tried with 1.1.37, and the latest version of the script still works for me... I'll try updating windows then I guess.

**Comment by ilreberli** [comment]
Got it running !

I have found a hint at https://www.reddit.com/r/AutoHotkey/comments/ub8d8x/ahk_studio_error_at_line_1_windows_11/
I created a new .ahk file and placed your script in it - works ! I do not understand clearly, but it seems to be a windows specific problem.
I will test now your changes and will give you feedback.

**Comment by 256shadesofgrey** [comment]
I see. Then it's again a case of #4 that I mention in the FAQ... It's just that the line in the error that you copied looks perfectly normal unlike in #4. That's not a windows issue then.

Either way, I'm glad it's sorted, enjoy.

**Comment by ilreberli** [comment]
Thank you very much, it's a great help for me, I'm at loggerheads with weaving.
I have Weaponset 1 and 2 bound with Up and Down keys, mapped with Logitech mouse buttons.
I also changed skillUltimate := "t" and suspendKey := "+Tab". Works all fine for me !

Thanks
