### ISSUE TITLE
what key to start

### ISSUE THREAD

**Issue by darkt1981** [256shadesofgrey/eso-light-attack-weave#3]
if tryed both yours and the other guys macro,
they do load and i can switch the state.
also i reset all controls back to default.
but i cant seem to figure out how to start the rotation?
i press ALT and Ctrl+alt on yours and right click.
but some how nothing seems to be fireing off.
what am i doeing wrong?

if used AHK a lot before some some weird reason i cant figure this one out...

**Comment by 256shadesofgrey** [comment]
If you use the macro with default settings, to toggle the macro on/off, use Tab. If that doesn't work, you probably started the macro before you started the game (as I wrote in usage instructions, the game must run before the macro does), or the game window is not active.

Also I'm not sure what you mean by "start the rotation". This macro only adds light attacks before the skills, it does not do the entire rotation for you. You press <1>, the macro does <left click>+<1> instead. You still have to do your rotation yourself, you just don't have to press 2 buttons every time you use a skill.

**Comment by darkt1981** [comment]
nope game was running before i started the macro system.
even compiled the macro to a .exe and ran as admin.
also screen was active and game running in full windows mode even tried normal windows mode.
Windows admin is completely disabled on my system still tried to run game and autohotkey as admin to be sure.
when i press Alt the auto hot key icoon does witch between S and H. but nothing happens in game.

system is fully updates including /Net frame and Visual installs.

when the addon is running and i press Alt, autohotkey is switching but the Toon is just standing there doeing nothing is just standing there.

**Comment by darkt1981** [comment]
does it auto attack or do i have to press and hold down a key for it to run ? seeing i dont see it in your info so im geussing not.

**Comment by 256shadesofgrey** [comment]
I haven't actually tried compiling it to an exe, I always run it with the interpreter. No admin permissions should be necessary.

Have you tried to actually do a rotation? When the icon switches to H, when you press 1, does it do a light attack before a skill or does it not?

**Comment by darkt1981** [comment]
ahh not didnt try that thought is worked like a macro, hold odwn left mouse and i runs let me check that xD

**Comment by darkt1981** [comment]
Yup seems to eb working now all of a sudden xD thanks for the info, not sure what went wrogn before haha thanks again.
