### ISSUE TITLE
Execute on gamepad

### ISSUE THREAD

**Issue by Weaver24251** [256shadesofgrey/eso-light-attack-weave#8]
Can this script be use on a pc gamepad while playing?

**Comment by 256shadesofgrey** [comment]
I haven't tried it, but theoretically yes. You will need to adjust the keybinds accordingly.

**Comment by Weaver24251** [comment]
What should I write to replace the keyboard keys for the gamepad buttons?

Thanks!

**Comment by 256shadesofgrey** [comment]
Adjust the values starting at this line: https://github.com/256shadesofgrey/eso-light-attack-weave/blob/44c0a089d9555aa2ede0adba18b93389e346887e/eso-light-attack-weave.ahk#L17 

According to this: https://www.autohotkey.com/docs/KeyList.htm#Joystick 

They also offer a test script there to figure out what button corresponds to which number in autohotkey. There is a link to it at the end of the "Joystick" section.
